# Generated by Django 3.2.7 on 2021-09-04 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('comment_by', models.IntegerField(blank=True, null=True)),
                ('card_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('wiki', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('when', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proj_creator', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='members_p', to=settings.AUTH_USER_MODEL)),
                ('project_admins', models.ManyToManyField(related_name='members_p_a', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menber_id', models.IntegerField(blank=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='headup.project')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_l', to='headup.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asignees', models.IntegerField(blank=True, null=True)),
                ('list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='headup.lists')),
            ],
        ),
    ]
