# Generated by Django 3.2.7 on 2021-09-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0002_alter_user_enrolment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
