# Generated by Django 3.2.7 on 2021-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0003_rename_name_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
