# Generated by Django 3.2.7 on 2021-09-07 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0004_alter_lists_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='asignees',
        ),
        migrations.AddField(
            model_name='cards',
            name='asignees',
            field=models.ManyToManyField(related_name='asignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
