# Generated by Django 3.2.7 on 2021-09-07 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0005_auto_20210907_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='menber_id',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='project_id',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_member', to='headup.project'),
        ),
    ]
