# Generated by Django 3.2.7 on 2021-10-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0011_auto_20211006_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lists',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
