# Generated by Django 3.2.7 on 2021-10-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0012_auto_20211006_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='members',
        ),
    ]
