# Generated by Django 3.2.7 on 2021-10-07 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0013_remove_lists_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='headup.lists'),
        ),
    ]
