# Generated by Django 3.2.7 on 2021-10-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0014_alter_cards_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
    ]
