# Generated by Django 3.2.7 on 2021-10-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headup', '0017_auto_20211009_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_by',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='comment',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_c', to='headup.cards'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
