# Generated by Django 3.2.7 on 2021-09-04 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('asignees', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('comment_by', models.IntegerField(blank=True, null=True)),
                ('card_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('wiki', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('when', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menber_id', models.IntegerField(blank=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Team Members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='headup.project')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Lists',
                'managed': False,
            },
        ),
    ]
